### ISSUE TITLE
Use Discord's command API

### ISSUE THREAD

**Issue by Iltotore** [bastianfbr/JS-Man#1]
JS-Man should use Discord's new command API for commands instead of old, deprecated, prefixed message.

## Motivations
This change would allow:
- Adding description without using the `help` command
- Grouping commands
- Auto completion

**Comment by WeeskyBDW** [comment]
The problem is that DJS do many (and imo stupids) changes who made JSBOT need many changes.

**Comment by bastianfbr** [comment]
JS-Man is replaced by Aym'Bot which uses the new version of the Discord.js API with SlashCommands, menus and buttons.

> [Link to Aym'bot repo](https://github.com/bastianfbr/Aym-Bot)
